language: python
dist: xenial

cache:
  - directories:
    - $HOME/miniconda

env:
  global:
    - DROP_DIR=$(pwd)
    - PROJECT_DIR="${HOME}/project"
    - MINICONDA_DIR="${HOME}/miniconda"
    - CONDA_SCRIPT="${MINICONDA_DIR}/etc/profile.d/conda.sh"
    - R_LIBS_USER="${MINICONDA_DIR}/envs/drop_env/lib/R/library"
    - TAR="/bin/tar"
    - BLD_DIR=${HOME}/bld-dir

python:
  - "3.7"

install:
  - cd $DROP_DIR
  - bash travis/install_conda.sh
  - source $CONDA_SCRIPT
  - conda install conda-build
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda config --add channels mumichae
  - travis_wait 30 conda build conda.recipe --output-folder $BLD_DIR
  - conda config --add channels "file://${BLD_DIR}"
  - conda config --get channels
  - conda create -q -n drop_env python=$TRAVIS_PYTHON_VERSION drop
  - conda activate drop_env
  - java -version
  - gatk --help
  - samtools --version
  - bcftools --version

before_script:
  - mkdir -p $PROJECT_DIR
  - cd $PROJECT_DIR
  - drop demo

script:
  - cd $PROJECT_DIR
  - snakemake -n
  - snakemake aberrantExpression --cores 2
  - snakemake aberrantSplicing --cores 2
  - snakemake mae --cores 2
  - snakemake --cores 2
  - snakemake exportCounts --cores 2
  
after_success:
  - conda env remove -n drop_env
