version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker: 
      - image: continuumio/anaconda3:latest
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Setup conda
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda init bash
            source $HOME/.bashrc
            conda update -q conda
            conda install python=3.7 conda-build
            conda config --add channels bioconda
            conda config --add channels conda-forge
      - run:
          name: Build conda package
          command: |
            conda build conda.recipe --output-folder=${HOME}/conda_build
            conda config --add channels "file://${HOME}/conda_build"
      - run:
          name: Conda environement
          command: |
            conda create -n drop python=3.7 drop
            conda activate drop
      - run:
          name: Set up Demo
          command: |
            mkdir -p $HOME/drop_demo
            cd $HOME/drop_demo
            drop demo
      - run:
          name: Run pipeline
          command: |
            snakemake -n
            snakemake aberrantExpression
            snakemake aberrantSplicing
            snakemake mae
            drop snakemake

workflows:
  main:
    jobs:
      - build-and-test
